---
kind: Service
apiVersion: v1
metadata:
  name: exampleservice
spec:
  selector:
    app: backend
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8081
      # Port to forward to inside the pod
      targetPort: 8080
      # Port accessible outside cluster
      nodePort: 30002
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myappdeployment
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          build: ./
          ports:
            - containerPort: 8080